### ISSUE TITLE
Job scheduler breaks on release mode

### ISSUE THREAD

**Issue by erik-seifert** [talkdirty/android_job_scheduler#8]
```
E/flutter ( 8931): Receiver: null
E/flutter ( 8931): Tried calling: call()
E/flutter ( 8931): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46)
E/flutter ( 8931): #1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279)
E/flutter ( 8931): #2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
```
It only occurs on release builds. No problem with development builds. The application must be closed.

Flutter doctor
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.0)
[✓] Connected devices (1 available)
```

**Comment by b-connect** [comment]
Moving function into main.dart fixes the problem.

**Comment by talkdirty** [comment]
Thanks for the detailed problem description. This is may be happening due
to unused Code Stripping Optimizations of the Dart Compiler on release
builds. Does the problem also occur if you reference the scheduled function
from somewhere else in your code?

On 9 Jul 2018 15:52, "Erik Seifert" <notifications@github.com> wrote:

Moving function into main.dart fixes the problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/talkdirty/android_job_scheduler/issues/8#issuecomment-403486750>,
or mute the thread

**Comment by b-connect** [comment]
It seems to be a problem, if the called function is not in main.dart . After move the function do main.dart all work like expected.
